Repository Alt-Org/Altzone, pull requests merged in 2025-02, with the labels that each got.

#366 Updated FlexibleGridLayout script
  Assets/MenuUi/Prefabs/UI Components/FlexibleGrid.prefab
  Assets/MenuUi/Prefabs/UI Components/FlexibleGrid.prefab.meta
  Assets/MenuUi/Scripts/FlexibleGridLayout/FlexibleGridLayout.cs
Labels: käyttöliittymä

#367 Fixed gallery loading bug and visual fixes
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/CharacterInventorySlot.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/DraggableCharacterGallery.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/DraggableCharacter.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelView.cs
Labels: käyttöliittymä

#368 Visual fixes to Character stats window
  Assets/MenuUi/Graphics/CommonGraphics/CommonPopup.png.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterInfoPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStatsPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStoryPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStoryPanel.prefab.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/ResourcePanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/ResourcePanel.prefab.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/StatUpdatePopUp.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/TabLineStatsWindow.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/NamePanel.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/NamePanel.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ResourcePanel.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ResourcePanel.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StoryPanel.cs
Labels: käyttöliittymä

#375 Cleaned the soulhome furniture reference from duplicate information.
  Assets/Altzone/Scripts/Reference Sheets/StorageFurnitureReference.cs
  Assets/MenuUi/Scripts/ReferenceSheets/SoulHomeFurnitureReference.cs
Labels: käyttöliittymä

#379 Created an ALtMonoBehaviout and moved some general use code there.
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/Altzone/Scripts/AltMonoBehaviour.cs.meta
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
  Assets/MenuUi/Scripts/Loader/LogInHandler.cs
  Assets/MenuUi/Scripts/TopPanel/ClanCoins.cs
Labels: käyttöliittymä

#380 ClanValue selector logic and handling fixes
  Assets/Altzone/Scripts/Model/Poco/Clan/ServerClan.cs
  Assets/MenuUi/Prefabs/Clan/ClanSettings.prefab
  Assets/MenuUi/Prefabs/Clan/CreateClan.prefab
  Assets/MenuUi/Scripts/Clan/ClanCreateNew.cs
  Assets/MenuUi/Scripts/Clan/ClanValuesViewManager.cs
  Assets/MenuUi/Scripts/Clan/ClanValuesViewManager.cs.meta
  Assets/MenuUi/Scripts/Clan/ValueLabels/ClanValuePanel.cs
  Assets/MenuUi/Scripts/Clan/ValueLabels/ValueLabelHandler.cs
  Assets/MenuUi/Scripts/Clan/ValueLabels/ValueSelectionController.cs
Labels: käyttöliittymä

#381 GridAutoScale fix
  Assets/Prg/Scripts/Common/Unity/GridAutoScale.cs
Labels: käyttöliittymä

#384 Changes to adding clan values to server
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanData.cs
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanDataTypes.cs
  Assets/MenuUi/Prefabs/Windows/Clan/ClanMainView.prefab
  Assets/MenuUi/Scripts/Clan/ClanCreateNew.cs
  Assets/MenuUi/Scripts/Clan/ClanHeartColorSetter.cs
  Assets/MenuUi/Scripts/Clan/ClanMainView.cs
Labels: käyttöliittymä

#386 Refactored popup before battle to use coroutine
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/SelectedCharactersPopup.prefab
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharactersPopup.cs
Labels: käyttöliittymä

#387 Money Panel Fixed
  Assets/MenuUi/Prefabs/Panels/ClanMoneyIncreasePanel.prefab
  Assets/MenuUi/Prefabs/Panels/ClanMoneyIncreasePanel.prefab.meta
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ClanMoneyItem.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Scripts/Clan/ClanMoneyBuyer.cs
  Assets/MenuUi/Scripts/Clan/ClanMoneyBuyer.cs.meta
  Assets/MenuUi/Scripts/Kauppa/ClanMoneyItem.cs
  Assets/MenuUi/Scripts/Kauppa/ClanMoneyItem.cs.meta
  Assets/MenuUi/Scripts/Kauppa/PanelActivnessController.cs
  Assets/MenuUi/Scripts/Kauppa/PanelActivnessController.cs.meta
  Assets/MenuUi/Scripts/Kauppa/PerusKauppaStorage.cs
  Assets/MenuUi/Scripts/Kauppa/ShopScrollViewResetter.cs
  Assets/MenuUi/Scripts/ListHelper.cs
  Assets/MenuUi/Scripts/ListHelper.cs.meta
  Assets/MenuUi/Scripts/TopPanel/ClanCoins.cs
Labels: käyttöliittymä

#389 Clan values are now shown in clan search
  Assets/MenuUi/Prefabs/Clan/ClanSearchListItem.prefab
  Assets/MenuUi/Scripts/Clan/ClanListing.cs
  Assets/MenuUi/Scripts/Clan/ValueLabels/ValueSelectionController.cs
Labels: käyttöliittymä

#390 UI/daily task/feature/dt updated tasks layout
  Assets/Altzone/Scripts/Model/Poco/Game/PlayerTask.cs
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCard.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskProgressMarker.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyQuest.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskOwnTask.cs
  Assets/MenuUi/Scripts/DailyQuest/Popup.cs
  Assets/MenuUi/Scripts/DailyQuest/PopupData.cs
Labels: käyttöliittymä

#393 Battlepopup small refactoring, defence characters showing on main page
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/SelectedCharacters.prefab
  Assets/MenuUi/Scripts/Lobby/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
Labels: käyttöliittymä

#396 Updated DailyTask serverCalls to new endpoint and formats
  Assets/Altzone/Scripts/Model/LocalModels.cs
  Assets/Altzone/Scripts/Model/Poco/Game/PlayerTask.cs
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/Altzone/Scripts/Storefront.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyQuest.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskClanPlayer.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
  Assets/MenuUi/Scripts/DailyQuest/PopupData.cs
Labels: käyttöliittymä

#398 Fixed battle popup swipe and main panel not showing bugs
  Assets/MenuUi/Prefabs/Panels/MainMenuViewSwipe.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyView.cs
Labels: käyttöliittymä

#402 The IntroStory selection is now saved to the server and provides the player with the starting battle characters.
  Assets/Altzone/Scripts/Model/CreateDefaultModels.cs
  Assets/Altzone/Scripts/Model/LocalModels.cs
  Assets/Altzone/Scripts/Model/Poco/Game/CustomCharacter.cs
  Assets/Altzone/Scripts/Model/Poco/Game/ServerCharacter.cs
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/Altzone/Scripts/Model/Poco/Player/ServerPlayer.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/Altzone/Scripts/Storefront.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelController.cs
  Assets/MenuUi/Scripts/Loader/HahmonValinta.cs
  Assets/MenuUi/Scripts/Loader/LogInHandler.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
Labels: käyttöliittymä

#405 UI/daily task/feature/daily task progress popup
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DTProgressManager.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DTProgressManager.prefab.meta
  Assets/MenuUi/Scenes/10-MenuUi.unity
  Assets/MenuUi/Scripts/DailyQuest/DailyQuest.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressPopup.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressPopup.cs.meta
Labels: käyttöliittymä

#409 Alt/audiomanager
  Assets/MenuUi/Audio/MenuBackground.wav
  Assets/MenuUi/Audio/MenuBackground.wav.meta
  Assets/MenuUi/Prefabs/Audio/AudioManager.prefab
  Assets/MenuUi/Prefabs/Audio/AudioSourceBlock.prefab
  Assets/MenuUi/Scripts/Audio.meta
  Assets/MenuUi/Scripts/Audio/AudioBlockHandler.cs
  Assets/MenuUi/Scripts/Audio/AudioBlockHandler.cs.meta
  Assets/MenuUi/Scripts/Audio/AudioManager.cs
  Assets/MenuUi/Scripts/Audio/AudioManager.cs.meta
  Assets/MenuUi/Scripts/Audio/MusicHandler.cs
  Assets/MenuUi/Scripts/Audio/MusicHandler.cs.meta
  Assets/MenuUi/Scripts/Audio/MusicList.cs
  Assets/MenuUi/Scripts/Audio/MusicList.cs.meta
  Assets/MenuUi/Scripts/MainMenu/MainMenuController.cs
  Assets/MenuUi/Scripts/Settings/PlayAudioClip.cs
  Assets/MenuUi/Scripts/SoulHome/SoulHomeController.cs
  Assets/MenuUi/Scripts/SoulHome/TowerController.cs
Labels: käyttöliittymä

#401 Updated furniture slot to match design
  Assets/MenuUi/Prefabs/UI Components/InvSlotObject.prefab
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
  Assets/MenuUi/Scripts/Varasto/InvSlotInfoHandler.cs
  Assets/MenuUi/Scripts/Varasto/InvSlotInfoHandler.cs.meta
Labels: käyttöliittymä

#411 Fixed the layering of the avatar and ladder in soulhome
  Assets/MenuUi/Graphics/SoulHomeGraphics/SoulHomeLadderBottomFloor.png.meta
  Assets/MenuUi/Graphics/SoulHomeGraphics/SoulHomeLadderMiddleFloor.png.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Room_Sideview.prefab
  Assets/MenuUi/Scripts/SoulHome/RoomData.cs
  Assets/MenuUi/Scripts/SoulHome/SoulHomeAvatarController.cs
Labels: käyttöliittymä

#410 Locking unowned characters in gallery and saving custom character to server, small fixes
  Assets/Altzone/Scripts/Model/Poco/Game/CustomCharacter.cs
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStatsPanel.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/GalleryCharacter.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelController.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelView.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/PieChartPreview.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/SlotBase.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/PieChart.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatUpdatePopUp.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsPanel.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsWindowController.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupCharacterSlotController.cs
Labels: käyttöliittymä

#412 Battle/feature - PlayerShieldSystem
  Assets/QuantumUser/Resources/Configs/ALTSystemConfig.asset
  Assets/QuantumUser/Resources/Prefabs/Player.prefab
  Assets/QuantumUser/Scripts/Player/PlayerSpriteChanger.cs
  Assets/QuantumUser/Scripts/Player/PlayerSpriteChanger.cs.meta
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/Events.qtn
  Assets/QuantumUser/Simulation/Qtn/Events.qtn.meta
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerShieldData.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerShieldData.qtn.meta
  Assets/QuantumUser/Simulation/Qtn/Player/SpawnIdentifier.qtn
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerShieldSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerShieldSystem.cs.meta
  Assets/QuantumUser/View/Generated/QPrototypePlayerShieldData.cs
  Assets/QuantumUser/View/Generated/QPrototypePlayerShieldData.cs.meta
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#413 Battle/fix - Removed player dragging
  Assets/QuantumUser/Scripts/Player/PlayerInput.cs
Labels: Quantum, battle

#414 UI/daily task/feature/dt clan milestone reward popup
  Assets/MenuUi/Animations/DailyTask.meta
  Assets/MenuUi/Animations/DailyTask/Moods.meta
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskAnimationMoodAngry.anim
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskAnimationMoodAngry.anim.meta
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskAnimationMoodSad.anim
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskAnimationMoodSad.anim.meta
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskMoodAngry.controller
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskMoodAngry.controller.meta
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskMoodSad.controller
  Assets/MenuUi/Animations/DailyTask/Moods/DailyTaskMoodSad.controller.meta
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskClanReward.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/Moods.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/Moods/DailyTaskMoodAngry.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/Moods/DailyTaskMoodAngry.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/Moods/DailyTaskMoodSad.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/Moods/DailyTaskMoodSad.prefab.meta
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskClanReward.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/Popup.cs
  Assets/MenuUi/Scripts/DailyQuest/PopupData.cs
Labels: käyttöliittymä

#415 Changes to Clan settings
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanData.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Prefabs/Clan/ClanSettings.prefab
  Assets/MenuUi/Scripts/Clan/ClanCreateNew.cs
  Assets/MenuUi/Scripts/Clan/ClanSettings.cs
Labels: käyttöliittymä

#418 Fix sorting furniture by name in storage
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
Labels: käyttöliittymä

#419 DT Clan players, minor visual update & progress popup bugfix
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskClanPlayer.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskClanPlayer.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressPopup.cs
Labels: käyttöliittymä

#417 Battle popup game type selection in main menu, and updated game background
  Assets/MenuUi/Graphics/CommonGraphics/CommonBackgroundCutout.png
  Assets/MenuUi/Graphics/CommonGraphics/CommonBackgroundCutout.png.meta
  Assets/MenuUi/Graphics/CommonGraphics/CommonBackgroundWall.png
  Assets/MenuUi/Graphics/CommonGraphics/CommonBackgroundWall.png.meta
  Assets/MenuUi/Graphics/HomeWindowGraphics/BattlePopUpNormal2v2.png
  Assets/MenuUi/Graphics/HomeWindowGraphics/BattlePopUpNormal2v2.png.meta
  Assets/MenuUi/Prefabs/Navigation/BT_ALTZONE.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/GameTypeOption.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/GameTypeOption.prefab.meta
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/SelectedCharacters.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
  Assets/MenuUi/Scripts/Lobby/BattleButton.meta
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs.meta
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs.meta
  Assets/MenuUi/Scripts/Lobby/GameTypeEnum.cs
  Assets/MenuUi/Scripts/Lobby/GameTypeEnum.cs.meta
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyView.cs
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.asset
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.asset.meta
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.cs
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.cs.meta
Labels: käyttöliittymä

#420 Grayscale shader for locked character slots
  Assets/MenuUi/Graphics/Shader/Grayscale.shader
  Assets/MenuUi/Graphics/Shader/Grayscale.shader.meta
  Assets/MenuUi/Graphics/Shader/GrayscaleMaterial.mat
  Assets/MenuUi/Graphics/Shader/GrayscaleMaterial.mat.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/GalleryCharacter.cs
Labels: käyttöliittymä

#421 Texture change script for TabLineBase
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/TabLineStatsWindow.prefab
  Assets/MenuUi/Prefabs/UI Components/TabLineBase.prefab
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeUI.cs
  Assets/MenuUi/Scripts/TabLine.meta
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
  Assets/MenuUi/Scripts/TabLine/TabLine.cs.meta
Labels: käyttöliittymä

#422 Added Patriootti animation
  Assets/MenuUi/Animations/Introduction.meta
  Assets/MenuUi/Animations/Introduction/IntroductionPatrioottiAnimationClip.anim
  Assets/MenuUi/Animations/Introduction/IntroductionPatrioottiAnimationClip.anim.meta
  Assets/MenuUi/Animations/Introduction/IntroductionPatrioottiSpriteSheet_0.controller
  Assets/MenuUi/Animations/Introduction/IntroductionPatrioottiSpriteSheet_0.controller.meta
  Assets/MenuUi/Introduction/Sprites/IntroductionPatrioottiSpriteSheet.png
  Assets/MenuUi/Introduction/Sprites/IntroductionPatrioottiSpriteSheet.png.meta
  Assets/MenuUi/Prefabs/Windows/IntroStory/CharacterIntroduction.prefab
Labels: käyttöliittymä

#423 ClanShop AdEditor new features
  Assets/MenuUi/Prefabs/ShopPrefabs/Ad/AdEditor.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdEditor.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdEditor.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdPopUp.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdPopUp.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Scripts/ShopAd/AdEditor.cs
Labels: käyttöliittymä

#430 Fixed a few issue with AudioManager where code activated out of context.
  Assets/MenuUi/Prefabs/Audio/AudioManager.prefab
  Assets/MenuUi/Scripts/Audio/AudioBlockHandler.cs
  Assets/MenuUi/Scripts/Audio/AudioManager.cs
  ProjectSettings/TagManager.asset
Labels: käyttöliittymä, äänet

#439 Battle/fix - Cleanup
  Assets/QuantumUser/Simulation/GameState.meta
  Assets/QuantumUser/Simulation/Player.meta
  Assets/QuantumUser/Simulation/RuntimeConfig.User.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSpawnerSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSpec.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/RuntimeConfig.Projectile.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/RuntimeConfig.Projectile.cs.meta
  Assets/QuantumUser/Simulation/Scripts/SoulWall/SoulWallSystem.cs
  Assets/QuantumUser/View/Player.meta
Labels: battle

#446 Grayscale shader fixes
  Assets/MenuUi/Graphics/Shader/Grayscale.shader
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/GalleryCharacter.cs
Labels: käyttöliittymä

#450 Battle/fix - ShieldTogglingRemoval
  Assets/QuantumUser/Resources/Configs/ALTSystemConfig.asset
  Assets/QuantumUser/Resources/Prefabs/Player.prefab
  Assets/QuantumUser/Scripts/Player/PlayerSpriteChanger.cs
  Assets/QuantumUser/Scripts/Player/PlayerSpriteChanger.cs.meta
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/Events.qtn
  Assets/QuantumUser/Simulation/Qtn/Events.qtn.meta
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerShieldData.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerShieldData.qtn.meta
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerShieldSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerShieldSystem.cs.meta
  Assets/QuantumUser/View/Generated/QPrototypePlayerShieldData.cs
  Assets/QuantumUser/View/Generated/QPrototypePlayerShieldData.cs.meta
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#454 Battle/feature - DebugStatsOverlay
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Scripts/UI/GameUiController.cs
  Assets/QuantumUser/Scripts/UI/GameViewController.cs
  Assets/QuantumUser/Scripts/UI/Views/GameUiDebugStatsOverlay.cs
  Assets/QuantumUser/Scripts/UI/Views/GameUiDebugStatsOverlay.cs.meta
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Qtn/DebugStatsOverlayEvent.qtn
  Assets/QuantumUser/Simulation/Qtn/DebugStatsOverlayEvent.qtn.meta
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerSpawnSystem.cs
Labels: battle

#456 Battle/feature - ChangingProjectileSprite
  Assets/Battle1/BattleGraphics/Projectiles/BattleProjectileAggressionBall.png.meta
  Assets/Battle1/BattleGraphics/Projectiles/BattleProjectileJoyBall.png.meta
  Assets/Battle1/BattleGraphics/Projectiles/BattleProjectileLoveBall.png.meta
  Assets/Battle1/BattleGraphics/Projectiles/BattleProjectilePlayfulBall.png.meta
  Assets/Battle1/BattleGraphics/Projectiles/BattleProjectileSadnessBall.png.meta
  Assets/QuantumUser/Resources/Prefabs/Projectile.prefab
  Assets/QuantumUser/Scripts/Projectile.meta
  Assets/QuantumUser/Scripts/Projectile/ProjectileSpriteChanger.cs
  Assets/QuantumUser/Scripts/Projectile/ProjectileSpriteChanger.cs.meta
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/Projectile/Projectile.qtn
  Assets/QuantumUser/Simulation/Qtn/Projectile/ProjectileEvents.qtn
  Assets/QuantumUser/Simulation/Qtn/Projectile/ProjectileEvents.qtn.meta
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSpawnerSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSystem.cs
Labels: Quantum, battle

#444 Battle/feature - GameControlSystem
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/MenuUi/Scenes/10-MenuUi.unity
  Assets/QuantumUser/Resources/Configs/ALTSystemConfig.asset
  Assets/QuantumUser/Resources/Prefabs/GameSessionEntity.prefab
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Simulation/RuntimeConfig.User.cs
  Assets/QuantumUser/Simulation/Scripts/Game/GameControlSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Game/GameControlSystem.cs.meta
  Assets/QuantumUser/Simulation/Scripts/GameState/GameSessionStateSystem.cs
Labels: battle

#460 AvatarEditor Avatar appears again
  Assets/MenuUi/Prefabs/AvatarEditor/CharacterImagePrefabs/CharacterImagePrefabTemplate.prefab
  Assets/MenuUi/Prefabs/AvatarEditor/CharacterImagePrefabs/ConfluenceAvatarImage.prefab
  Assets/MenuUi/Prefabs/Windows/Avatar/AvatarEditor.prefab
  Assets/MenuUi/Scripts/AvatarEditor/CharacterLoader.cs
Labels: käyttöliittymä

#466 Debug window with option to add locked character to account and small fixes
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterInfoPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStatsPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/DebugPopUp.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/DebugPopUp.prefab.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/StatUpdatePopUp.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/TabLineStatsWindow.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelController.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/DebugPopUp.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/DebugPopUp.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatUpdatePopUp.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsWindowController.cs
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
Labels: käyttöliittymä

#461 Added Nukkuja animation to character introduction
  Assets/MenuUi/Animations/Introduction/IntroductionNukkujaAnimationClip.anim
  Assets/MenuUi/Animations/Introduction/IntroductionNukkujaAnimationClip.anim.meta
  Assets/MenuUi/Animations/Introduction/IntroductionNukkujaSpriteSheet_0.controller
  Assets/MenuUi/Animations/Introduction/IntroductionNukkujaSpriteSheet_0.controller.meta
  Assets/MenuUi/Introduction/Sprites/IntroductionNukkujaSpriteSheet.png
  Assets/MenuUi/Introduction/Sprites/IntroductionNukkujaSpriteSheet.png.meta
  Assets/MenuUi/Prefabs/Windows/IntroStory/CharacterIntroduction.prefab
Labels: käyttöliittymä

#469 UI/daily task/feature/mood functionality&tab buttons down position
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCard.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskOwnTask.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressPopup.cs
  Assets/MenuUi/Scripts/DailyQuest/TabButtonsVisualController.cs
  Assets/MenuUi/Scripts/DailyQuest/TabButtonsVisualController.cs.meta
Labels: käyttöliittymä
