Repository Alt-Org/Altzone, pull requests merged in 2025-03, with the labels that each got.

#470 Chat fixes
  Assets/MenuUi/Prefabs/Chat/BlueMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OrangeMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherBlueMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherOrangeMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherPinkMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherRedMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherYellowMessage.prefab
  Assets/MenuUi/Prefabs/Chat/PinkMessage.prefab
  Assets/MenuUi/Prefabs/Chat/RedMessage.prefab
  Assets/MenuUi/Prefabs/Chat/YellowMessage.prefab
  Assets/MenuUi/Prefabs/Windows/GlobalWindows/ChatView.prefab
  Assets/MenuUi/Scripts/Chat/Chat.cs
Labels: käyttöliittymä

#474 Update info panel to match design document
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
Labels: käyttöliittymä

#485 Fix furniture slot scaling in storage
  Assets/MenuUi/Prefabs/UI Components/InvSlotObject.prefab
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
Labels: käyttöliittymä

#482 Battle/feature - ExitBattle
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Scripts/UI/Views/GameUiGameOverHandler.cs
Labels: Quantum, battle

#481 Battle/fix - BattleHotFixes
  Assets/QuantumUser/Resources/Prefabs/Projectile.prefab
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Scripts/Player/PlayerInput.cs
  Assets/QuantumUser/Scripts/Projectile/ProjectileSpriteChanger.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/SoulWall/SoulWall.qtn
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSystem.cs
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#484 AvatarEditor save & load, bug fix & code readability
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs.meta
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Clothes/Avatar301Clothes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Clothes/Avatar401Clothes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar301Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar401Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar501Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar601-1Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar601-2Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Eyes/Avatar701Eyes.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/HairHat/Avatar301Hair.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/HairHat/Avatar401Hair.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/HairHat/Avatar501Hair.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/HairHat/Avatar601-1Hair.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/HairHat/Avatar601-2Hair.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Mouth/Avatar301Mouth.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Mouth/Avatar401Mouth.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Mouth/Avatar501Mouth.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Mouth/Avatar601Mouth.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Mouth/Avatar701Mouth.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Nose/Avatar301Nose.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Nose/Avatar401Nose.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Nose/Avatar501Nose.png.meta
  Assets/MenuUi/Graphics/AvatarGraphics/AvatarFeatures/Nose/Avatar601Nose.png.meta
  Assets/MenuUi/Prefabs/Windows/Avatar/AvatarEditor.prefab
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorController.cs
  Assets/MenuUi/Scripts/AvatarEditor/CharacterLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/ColorPicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/FeaturePicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/PlayerAvatar.cs
Labels: käyttöliittymä

#488 Battle/feature - BattleCamera
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Scripts/Game.meta
  Assets/QuantumUser/Scripts/Game/BattleCamera.cs
  Assets/QuantumUser/Scripts/Game/BattleCamera.cs.meta
  Assets/QuantumUser/Scripts/Player/PlayerInput.cs
Labels: battle

#490 Fixes to chat message selection, tabline added
  Assets/MenuUi/Prefabs/Chat/BlueMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OrangeMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherBlueMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherOrangeMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherPinkMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherRedMessage.prefab
  Assets/MenuUi/Prefabs/Chat/OtherYellowMessage.prefab
  Assets/MenuUi/Prefabs/Chat/PinkMessage.prefab
  Assets/MenuUi/Prefabs/Chat/RedMessage.prefab
  Assets/MenuUi/Prefabs/Chat/YellowMessage.prefab
  Assets/MenuUi/Prefabs/Windows/GlobalWindows/ChatView.prefab
  Assets/MenuUi/Scripts/Chat/Chat.cs
  Assets/MenuUi/Scripts/Chat/ChatController.cs
Labels: käyttöliittymä

#493 UI/daily task/feature/education functionality
  Assets/Altzone/Scripts/Model/Poco/Game/PlayerTask.cs
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCard.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskClanReward.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyQuest.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressListener.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
  Assets/MenuUi/Scripts/DailyQuest/Popup.cs
Labels: käyttöliittymä

#491 Updated battle popup UI layout and bug fixes
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Photon/LobbyPlayer.cs
  Assets/Altzone/Scripts/Photon/LobbyRoom.cs
  Assets/Altzone/Scripts/Photon/LobbyRoomInfo.cs
  Assets/Altzone/Scripts/Photon/PhotonBattleRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonRealtimeClient.cs
  Assets/Altzone/Scripts/Photon/PhotonRoomList.cs
  Assets/MenuUi/Prefabs/Navigation/BT_ALTZONE.prefab
  Assets/MenuUi/Prefabs/Panels/MainMenuViewSwipe.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/BattlePopupSelectedCharacter.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/BattlePopupSelectedCharacter.prefab.meta
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/GameTypeOption.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/RoomSlot.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/SelectedCharacters.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelController.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelView.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/PieChartPreview.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/DebugPopUp.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupPanelManager.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupPanelManager.cs.meta
  Assets/MenuUi/Scripts/Lobby/CreateRoom.meta
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CreateRoomCustom.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CreateRoomCustom.cs.meta
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/PasswordPopup.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/PasswordPopup.cs.meta
  Assets/MenuUi/Scripts/Lobby/InLobby/RoomSlot.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/RoomSlot.cs.meta
  Assets/MenuUi/Scripts/Lobby/InRoom/PaneInRoom.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/RoomSearchPanelController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters.meta
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs.meta
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs.meta
  Assets/MenuUi/Scripts/Lobby/SelectedCharactersPopup.cs
Labels: käyttöliittymä

#489 Battle/feature - PlayerManager
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/QuantumUser/Resources/Configs/ALTSystemConfig.asset
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Simulation/BattleCharacterBase.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/Game/BattleConstants.qtn
  Assets/QuantumUser/Simulation/Qtn/Game/BattleConstants.qtn.meta
  Assets/QuantumUser/Simulation/Qtn/Game/BattleTeamNumber.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/BattlePlayerPosition.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerData.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerManagerData.qtn
  Assets/QuantumUser/Simulation/Qtn/Player/PlayerManagerData.qtn.meta
  Assets/QuantumUser/Simulation/RuntimePlayer.User.cs
  Assets/QuantumUser/Simulation/Scripts/Game/GameControlSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerJoinSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerJoinSystem.cs.meta
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerManager.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerManager.cs.meta
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerMovementSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Player/PlayerSpawnSystem.cs
  Assets/QuantumUser/View/Generated/QPrototypePlayerManagerData.cs
  Assets/QuantumUser/View/Generated/QPrototypePlayerManagerData.cs.meta
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#499 Hotfixes to 151.
  Assets/BattleStartHandler.cs
  Assets/BattleStartHandler.cs.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/FurniturePostersGraphics/PosterSofaUni.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/FurniturePostersGraphics/PosterSofaUni4K.PNG.meta
  Assets/MenuUi/Prefabs/Audio/AudioManager.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStart.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStoryController.cs
  Assets/MenuUi/Prefabs/Windows/Startup/LogInView.prefab
  Assets/MenuUi/Prefabs/Windows/Startup/PrivacyPolicyView.prefab
  Assets/MenuUi/Scripts/Audio/MusicHandler.cs
  Assets/MenuUi/Scripts/Loader/LoadingInfoController.cs
  Assets/MenuUi/Scripts/Loader/LogInHandler.cs
  Assets/MenuUi/Scripts/PrivacyPolicy/TMProUGUIHyperlinks.cs
Labels: käyttöliittymä

#498 DT Fixed missing textures in Owntask
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
Labels: käyttöliittymä

#497 Small layout changes to home screen
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
Labels: käyttöliittymä

#500 DT Renamed a ServerPlayerTask class variable
  Assets/Altzone/Scripts/Model/Poco/Game/PlayerTask.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
Labels: bug, käyttöliittymä

#501 Switched projector and obedient class colors and updated inventory slot visuals
  Assets/Altzone/Resources/Characters/ClassColorReference.asset
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/CharacterInventorySlot.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/CharacterSlot.cs
Labels: käyttöliittymä

#503 Add unowned character from gallery and swipe back from character stats window
  Assets/Altzone/Resources/Characters/CharacterSpec_102.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_201.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_401.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_603.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_701.asset
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/CharacterInventorySlot.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/GalleryCharacter.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelView.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/SwipeBack.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/SwipeBack.cs.meta
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeUI.cs
Labels: käyttöliittymä

#504 Created a new furniture builder and added Sofa_Uni
  Assets/Altzone/Scripts/Model/Poco/Game/GameFurniture.cs
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Reference Sheets/StorageFurnitureReference.asset
  Assets/Altzone/Scripts/Reference Sheets/StorageFurnitureReference.cs
  Assets/MenuUi/Graphics/FurnitureGraphics/FurniturePostersGraphics/PosterSofaUni.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Uni/FurnitureUniSofa.png.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/FurnitureBuilder.asset
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/FurnitureBuilder.asset.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/FurnitureBuilder.cs
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/FurnitureBuilder.cs.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Sofa_Uni_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Sofa_Uni_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Sofa_Uni_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Sofa_Uni_FurnitureImage.prefab.meta
  Assets/MenuUi/Scripts/ReferenceSheets/SoulHomeFurnitureReference.cs
  Assets/MenuUi/Scripts/ReferenceSheets/SoulhomeFurnitureReference.asset
  Assets/MenuUi/Scripts/SoulHome/Furniture.cs
  Assets/MenuUi/Scripts/SoulHome/FurnitureHandling.cs
  Assets/MenuUi/Scripts/SoulHome/TrayFurniture.cs
Labels: käyttöliittymä

#505 Battle popup code refactoring and commenting
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Photon/PhotonBattleRoom.cs
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupHeightSetter.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupHeightSetter.cs.meta
  Assets/MenuUi/Scripts/Lobby/BattlePopupPanelManager.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CreateRoomCustom.cs
  Assets/MenuUi/Scripts/Lobby/CustomBattleGameModeSelector.cs
  Assets/MenuUi/Scripts/Lobby/GameTypeEnum.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyView.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingView.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/PasswordPopup.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/RoomSlot.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/TopInfoPanelController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/TopInfoPanelController.cs.meta
  Assets/MenuUi/Scripts/Lobby/InRoom/InRoomController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/InRoomController.cs.meta
  Assets/MenuUi/Scripts/Lobby/InRoom/PanePlayerListing.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/PanePlayerListing.cs.meta
  Assets/MenuUi/Scripts/Lobby/InRoom/PlayerPositionButtons.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/PlayerPositionButtons.cs.meta
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/LobbyWindowNavigationHandler.cs
  Assets/MenuUi/Scripts/Lobby/RoomSearchPanelController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.cs
Labels: documentation, käyttöliittymä

#496 TabLineBase code update
  Assets/MenuUi/Prefabs/Canvas/UICanvas.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/TabLineStatsWindow.prefab
  Assets/MenuUi/Prefabs/UI Components/TabLineBase.prefab
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
Labels: käyttöliittymä

#508 UI/daily task/feature/task type long click
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskLongPress.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskLongPress.cs.meta
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressListener.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressManager.cs
Labels: käyttöliittymä

#511 Removed SelectedCharacters popup before battle
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Photon/PhotonBattleRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonLobbyRoom.cs
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/SelectedCharactersPopup.prefab
  Assets/MenuUi/Prefabs/UI Components/SelectedCharactersPopup.prefab.meta
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/InRoomController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharactersPopup.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharactersPopup.cs.meta
Labels: käyttöliittymä

#509 Updated CharacterStatsWindow UI to match Figma
  Assets/MenuUi/Graphics/CommonGraphics/CommonPopup.png.meta
  Assets/MenuUi/Graphics/DefencegalleryGraphics/DefencegalleryLoadoutOne.png.meta
  Assets/MenuUi/Graphics/DefencegalleryGraphics/DefencegalleryLoadoutThree.png.meta
  Assets/MenuUi/Graphics/DefencegalleryGraphics/DefencegalleryLoadoutTwo.png.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/CharacterInventorySlot.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterInfoPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterStatsPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/ResourcePanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/TabLineStatsWindow.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/BattlePopupSelectedCharacter.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/PieChartPreview.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ClassColorSetter.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ClassColorSetter.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/InfoPanel.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/LoadoutButton.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/LoadoutButton.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/PieChart.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsWindowController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
  Assets/MenuUi/Scripts/ReferenceSheets/PiechartReference.asset
Labels: käyttöliittymä

#513 Character gallery filtering options created
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryPanel.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelView.cs
  Assets/MenuUi/Scripts/FlexibleGridLayout/FlexibleGridLayout.cs
Labels: käyttöliittymä

#514 Added diamond and eraser functionality to stats window debug popup
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/DebugPopUp.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/DebugPopUp.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ResourcePanel.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsWindowController.cs
Labels: käyttöliittymä

#529 Battle/fix - Goal areas moved
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
Labels: Quantum, battle

#536 Battle/feature - ScreenEffect and Projectile refactor
  Assets/Battle1/BattleGraphics/Effects.meta
  Assets/Battle1/BattleGraphics/Effects/ScreenEffect.png
  Assets/Battle1/BattleGraphics/Effects/ScreenEffect.png.meta
  Assets/Battle1/BattleGraphics/Effects/Sparkle.png
  Assets/Battle1/BattleGraphics/Effects/Sparkle.png.meta
  Assets/Battle1/BattleGraphics/Effects/SparkleMaterial.mat
  Assets/Battle1/BattleGraphics/Effects/SparkleMaterial.mat.meta
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/QuantumGameScene.unity
  Assets/QuantumUser/Scripts/Effects.meta
  Assets/QuantumUser/Scripts/Effects/ScreenEffectViewController.cs
  Assets/QuantumUser/Scripts/Effects/ScreenEffectViewController.cs.meta
  Assets/QuantumUser/Scripts/Projectile/ProjectileViewController.cs
  Assets/QuantumUser/Scripts/Projectile/ProjectileViewController.cs.meta
  Assets/QuantumUser/Scripts/UI/GameViewController.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/Projectile/EmotionState.qtn
  Assets/QuantumUser/Simulation/Qtn/Projectile/EmotionState.qtn.meta
  Assets/QuantumUser/Simulation/Qtn/Projectile/Projectile.qtn
  Assets/QuantumUser/Simulation/Qtn/Projectile/ProjectileEvents.qtn
  Assets/QuantumUser/Simulation/Qtn/SoulWall/SoulWall.qtn
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSpawnerSystem.cs
  Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSystem.cs
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#517 UI/avatar editor/feature/load avatar to scriptable object
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs
  Assets/Altzone/Scripts/Reference Sheets/AvatarDefaultReference.cs
  Assets/Altzone/Scripts/Reference Sheets/AvatarDefaultReference.cs.meta
  Assets/Altzone/Scripts/Reference Sheets/AvatarPartsReference.cs
  Assets/Altzone/Scripts/Reference Sheets/AvatarPartsReference.cs.meta
  Assets/MenuUi/Prefabs/AvatarEditor/AvatarDefaults.asset
  Assets/MenuUi/Prefabs/AvatarEditor/AvatarDefaults.asset.meta
  Assets/MenuUi/Prefabs/AvatarEditor/AvatarParts.asset
  Assets/MenuUi/Prefabs/AvatarEditor/AvatarParts.asset.meta
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Windows/Avatar/AvatarEditor.prefab
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs.meta
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorCharacterHandle.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorCharacterHandle.cs.meta
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorController.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorFeatureButtonsHandler.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorFeatureButtonsHandler.cs.meta
  Assets/MenuUi/Scripts/AvatarEditor/CharacterLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/ColorPicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/Enums/FeatureID.cs
  Assets/MenuUi/Scripts/AvatarEditor/Enums/FeatureSlot.cs
  Assets/MenuUi/Scripts/AvatarEditor/FeatureData.cs
  Assets/MenuUi/Scripts/AvatarEditor/FeaturePicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/PlayerAvatar.cs
Labels: käyttöliittymä

#531 UI/varasto/feature/filtering
  Assets/MenuUi/Prefabs/UI Components/InvSlotObject.prefab
  Assets/MenuUi/Prefabs/Varasto.meta
  Assets/MenuUi/Prefabs/Varasto/SetToggle.prefab
  Assets/MenuUi/Prefabs/Varasto/SetToggle.prefab.meta
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
  Assets/MenuUi/Scripts/Varasto/SetFilterHandler.cs
  Assets/MenuUi/Scripts/Varasto/SetFilterHandler.cs.meta
  Assets/MenuUi/Scripts/Varasto/ValueSlider.cs
  Assets/MenuUi/Scripts/Varasto/ValueSlider.cs.meta
Labels: käyttöliittymä

#546 Added new ServerCalls
  Assets/Altzone/Scripts/ServerManager.cs
Labels: käyttöliittymä

#543 Battle/refactor - OrganizeBattle
  Assets/Battle1/Scenes/scene-newbattle-game.asset
  Assets/QuantumUser/Resources/Graphics/Background.meta
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1Background.png
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1Background.png.meta
  Assets/QuantumUser/Resources/Graphics/Effects.meta
  Assets/QuantumUser/Resources/Graphics/Effects/ScreenEffect.png
  Assets/QuantumUser/Resources/Graphics/Effects/ScreenEffect.png.meta
  Assets/QuantumUser/Resources/Graphics/Effects/Sparkle.png
  Assets/QuantumUser/Resources/Graphics/Effects/Sparkle.png.meta
  Assets/QuantumUser/Resources/Graphics/Effects/SparkleMaterial.mat
  Assets/QuantumUser/Resources/Graphics/Effects/SparkleMaterial.mat.meta
  Assets/QuantumUser/Resources/Prefabs/GameUI.prefab
  Assets/QuantumUser/Resources/Prefabs/Player.meta
  Assets/QuantumUser/Resources/Prefabs/Player/Player.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/Player.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/Player/PlayerEntityPrototype.qprototype
  Assets/QuantumUser/Resources/Prefabs/Player/PlayerEntityPrototype.qprototype.meta
  Assets/QuantumUser/Resources/Prefabs/Projectile.meta
  Assets/QuantumUser/Resources/Prefabs/Projectile/Projectile.prefab
  Assets/QuantumUser/Resources/Prefabs/Projectile/Projectile.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/Projectile/ProjectileEntityPrototype.qprototype
  Assets/QuantumUser/Resources/Prefabs/Projectile/ProjectileEntityPrototype.qprototype.meta
  Assets/QuantumUser/Resources/Prefabs/ShieldEntity.prefab
  Assets/QuantumUser/Resources/Prefabs/ShieldEntityEntityPrototype.qprototype
  Assets/QuantumUser/Resources/Prefabs/ShieldEntityEntityPrototype.qprototype.meta
  Assets/QuantumUser/Resources/Prefabs/Simulation.meta
  Assets/QuantumUser/Resources/Prefabs/Simulation/BattleSimulationData.prefab
  Assets/QuantumUser/Resources/Prefabs/Simulation/BattleSimulationData.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/Simulation/BattleSimulationDataEntityPrototype.qprototype
  Assets/QuantumUser/Resources/Prefabs/Simulation/BattleSimulationDataEntityPrototype.qprototype.meta
  Assets/QuantumUser/Resources/Prefabs/Ui.meta
  Assets/QuantumUser/Resources/Prefabs/Ui/BattleUi.prefab
  Assets/QuantumUser/Resources/Prefabs/Ui/BattleUi.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/ViewController.meta
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleGameViewController.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleGameViewController.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleGridViewController.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleGridViewController.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleScreenEffectViewController.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleScreenEffectViewController.prefab.meta
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity.meta
  Assets/QuantumUser/Scenes/32-QuantumBattle_TestGrid.unity
  Assets/QuantumUser/Scenes/32-QuantumBattle_TestGrid.unity.meta
  Assets/QuantumUser/Scenes/Tests/QuantumTestScene_BlockSoulWall.unity
  Assets/QuantumUser/Scripts/Effects/ScreenEffectViewController.cs
  Assets/QuantumUser/Scripts/Game/GameViewController.cs
  Assets/QuantumUser/Scripts/Game/GameViewController.cs.meta
  Assets/QuantumUser/Scripts/Grid/GridViewController.cs
  Assets/QuantumUser/Scripts/Player/PlayerInput.cs
  Assets/QuantumUser/Scripts/Player/PlayerViewController.cs
  Assets/QuantumUser/Scripts/Projectile/ProjectileViewController.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Quantum, battle

#551 Updated the swipe scrolling to work even if the scroll rect doesn't directly receive the drag.
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/DebugPopUp.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/StatUpdatePopUp.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/CharacterStatsWindowView.prefab
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeBlocker.cs
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeUI.cs
Labels: käyttöliittymä

#554 Updated the SoulHome sprite layering
  Assets/MenuUi/Prefabs/Windows/SoulHome/AvatarPrefabs/Avatar_Character.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Base_FurniturePrefab.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/ArmChair_Rakkaus_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/Bed_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/Carpet_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/Closet_Rakkaus_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/CoffeeTable_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/DiningTable_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/Mirror_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Love/Sofa_Love_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Armchair_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Coffeetable_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Commode_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Drawings_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Ficus_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Flowers_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/NewCarpet_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/NewWindow_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/OldCarpet_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/OldWindow_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Painting_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Pictures_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Sofa_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Memories/Toyfox_Memories_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Neuro/Chair_Neuro_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Neuro/Clock_Neuro_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Neuro/Dresser_Neuro_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Neuro/Stool_Neuro_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Polarity/Bookshelf_Polarity_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Polarity/Chair_Polarity_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Polarity/Table_Polarity_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Schrodinger/Bathtub_Schrodinger_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Schrodinger/Carpet_Schrodinger_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Schrodinger/Mirror_Schrodinger_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Schrodinger/Sink_Schrodinger_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Schrodinger/Toilet_Schrodinger_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/ArmChair_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/Closet_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/CoffeeTable_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/Floorlamp_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/Mirror_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/SideTable_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Taakka/Sofa_Taakka_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Room_Sideview.prefab
  Assets/MenuUi/Scripts/SoulHome/FurnitureHandling.cs
  Assets/MenuUi/Scripts/SoulHome/RoomData.cs
  Assets/MenuUi/Scripts/SoulHome/SoulHomeAvatarController.cs
  Assets/MenuUi/Scripts/SoulHome/TowerController.cs
Labels: käyttöliittymä

#552 UI/daily task/feature/improved scroll functionality
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard1000.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard1000.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard1500.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard1500.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard500.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCard500.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardAction.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardAction.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardCulture.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardCulture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardEthical.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardEthical.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardSocial.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardSocial.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardStory.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskCards/DailyTaskCardStory.prefab.meta
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/ScrollManager.meta
  Assets/MenuUi/Scripts/DailyQuest/ScrollManager/BaseScrollRectVariant.cs
  Assets/MenuUi/Scripts/DailyQuest/ScrollManager/BaseScrollRectVariant.cs.meta
  Assets/MenuUi/Scripts/DailyQuest/ScrollManager/ScrollLocalManager.cs
  Assets/MenuUi/Scripts/DailyQuest/ScrollManager/ScrollLocalManager.cs.meta
Labels: käyttöliittymä

#553 Clan 2v2 and Random 2v2 (collector match) initial matchmaking
  Assets/Altzone/Resources/BattleMapReference.asset
  Assets/Altzone/Resources/BattleMapReference.asset.meta
  Assets/Altzone/Resources/BattleMaps.meta
  Assets/Altzone/Resources/BattleMaps/BattleMap_cafe.asset
  Assets/Altzone/Resources/BattleMaps/BattleMap_cafe.asset.meta
  Assets/Altzone/Scripts/EmotionEnum.cs
  Assets/Altzone/Scripts/ModelV2/BattleMap.cs
  Assets/Altzone/Scripts/ModelV2/BattleMap.cs.meta
  Assets/Altzone/Scripts/ModelV2/BattleMapReference.cs
  Assets/Altzone/Scripts/ModelV2/BattleMapReference.cs.meta
  Assets/Altzone/Scripts/Photon/GameTypeEnum.cs
  Assets/Altzone/Scripts/Photon/GameTypeEnum.cs.meta
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Photon/PhotonBattleRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonLobbyRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonRealtimeClient.cs
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Resources/GalleryCharacterReference.asset
  Assets/MenuUi/Resources/GalleryCharacterReference.asset.meta
  Assets/MenuUi/Resources/GameTypeReference.asset
  Assets/MenuUi/Resources/GameTypeReference.asset.meta
  Assets/MenuUi/Resources/LabelReference.asset
  Assets/MenuUi/Resources/LabelReference.asset.meta
  Assets/MenuUi/Resources/PiechartReference.asset
  Assets/MenuUi/Resources/PiechartReference.asset.meta
  Assets/MenuUi/Resources/SoulhomeFurnitureReference.asset
  Assets/MenuUi/Resources/SoulhomeFurnitureReference.asset.meta
  Assets/MenuUi/Resources/StatsReference.asset
  Assets/MenuUi/Resources/StatsReference.asset.meta
  Assets/MenuUi/Scenes/10-MenuUi.unity
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupPanelManager.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CreateRoomCustom.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CustomBattleGameModeSelector.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CustomBattleGameModeSelector.cs.meta
  Assets/MenuUi/Scripts/Lobby/CreateRoom/MapAndRoomNameSelector.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/MapAndRoomNameSelector.cs.meta
  Assets/MenuUi/Scripts/Lobby/CustomBattleGameModeSelector.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/InRoomController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/MatchmakingPanel.cs
  Assets/MenuUi/Scripts/Lobby/MatchmakingPanel.cs.meta
  Assets/MenuUi/Scripts/Lobby/PhotonBattleLobbyRoom.cs
  Assets/MenuUi/Scripts/Lobby/RoomSearchPanelController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.cs
  Assets/QuantumUser/Simulation/RuntimeConfig.User.cs
Labels: käyttöliittymä

#555 AvatarEditor visual updates on save
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/Altzone/Scripts/Reference Sheets/AvatarPartsReference.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Prefabs/AvatarEditor/CharacterImagePrefabs/CharacterHeadImage.prefab
  Assets/MenuUi/Prefabs/AvatarEditor/CharacterImagePrefabs/CharacterImagePrefabTemplate.prefab
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorCharacterHandle.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorController.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarFaceLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarLoader.cs.meta
  Assets/MenuUi/Scripts/AvatarEditor/ColorPicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/FeaturePicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/PlayerAvatar.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/ModelController.cs
Labels: käyttöliittymä

#557 UI/shop/feature/clan shop
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempBackToTheFuture.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempDistrict9.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempDune.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempJaws.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempParasite.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempShining.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempSpaceOdessey.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempUp.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempWalle.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempWorldwarZ.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandHourglass.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectArrow.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectHeart.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectLightning.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectSpikyBubble.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectSpiral.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandShopEffectStar.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBorderGreed.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxBackground.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxBase.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxBordersBase.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxBordersLighting.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxBordersLogo.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxEffectsBase.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxEffectsDetail.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxEffectsLighting.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxEffectsLogo.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxInventoryDetail.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxInventoryLighting.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBoxInventoryLogo.png.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdEditor.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdPopUp.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdPopUp.prefab.meta
  Assets/MenuUi/Scripts/ShopAd/AdEditor.cs
  Assets/MenuUi/Scripts/ShopAd/ChooseBox.cs
  Assets/MenuUi/Scripts/ShopAd/ChooseBox.cs.meta
Labels: käyttöliittymä

#562 UI/avatar editor/feature/reset default and previous visuals
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs
  Assets/MenuUi/Prefabs/Windows/Avatar/AvatarEditor.prefab
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorController.cs
  Assets/MenuUi/Scripts/AvatarEditor/PlayerAvatar.cs
Labels: käyttöliittymä

#563 TabLine script updated and couple of bug fixes
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/TabButtonsVisualController.cs
  Assets/MenuUi/Scripts/DailyQuest/TabButtonsVisualController.cs.meta
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/ClassColorSetter.cs
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
Labels: käyttöliittymä

#565 BattlePopup bug fixes
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/MenuUi/Graphics/CommonGraphics/CommonLock.png
  Assets/MenuUi/Graphics/CommonGraphics/CommonLockOpen.png
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/RoomSlot.prefab
  Assets/MenuUi/Scenes/10-MenuUi.unity
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
Labels: käyttöliittymä
