Repository Alt-Org/Altzone, pull requests merged in 2025-04, with the labels that each got.

#569 Battle/fix - BattleRescale
  Assets/QuantumUser/Resources/Graphics/Projectile.meta
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileAggressionBall.png
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileAggressionBall.png.meta
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileJoyBall.png
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileJoyBall.png.meta
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileLoveBall.png
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileLoveBall.png.meta
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectilePlayfulBall.png
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectilePlayfulBall.png.meta
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileSadnessBall.png
  Assets/QuantumUser/Resources/Graphics/Projectile/BattleProjectileSadnessBall.png.meta
  Assets/QuantumUser/Resources/Prefabs/Projectile/Projectile.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/SoulWallBaseViewModel.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/SoulWallSegmentType1.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/SoulWallSegmentType2.prefab
  Assets/QuantumUser/Resources/Specs/BattleArenaSpec.asset
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/Simulation/Qtn/SoulWall/SoulWall.qtn
  Assets/QuantumUser/Simulation/Scripts/SoulWall/SoulWallSystem.cs
Labels: Quantum, battle

#570 Updated trickster class colors to ClassColorReference
  Assets/Altzone/Resources/Characters/ClassColorReference.asset
Labels: käyttöliittymä

#572 Chat quick responses added
  Assets/MenuUi/Prefabs/Windows/GlobalWindows/ChatView.prefab
  Assets/MenuUi/Scripts/Chat/Chat.cs
  Assets/MenuUi/Scripts/Chat/ChatResponse.cs
  Assets/MenuUi/Scripts/Chat/ChatResponse.cs.meta
  Assets/MenuUi/Scripts/Chat/ChatResponseList.asset
  Assets/MenuUi/Scripts/Chat/ChatResponseList.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponseList.cs
  Assets/MenuUi/Scripts/Chat/ChatResponseList.cs.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Confluent.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Confluent.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Default.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Default.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Desensitizer.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Desensitizer.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Intellectualizer.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Intellectualizer.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Obedient.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Obedient.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Projector.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Projector.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Retroflector.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Retroflector.asset.meta
  Assets/MenuUi/Scripts/Chat/ChatResponse_Trickster.asset
  Assets/MenuUi/Scripts/Chat/ChatResponse_Trickster.asset.meta
  Assets/MenuUi/Scripts/Chat/QuickResponceHandler.cs
  Assets/MenuUi/Scripts/Chat/QuickResponceHandler.cs.meta
  Assets/MenuUi/Scripts/Chat/QuickResponse.prefab
  Assets/MenuUi/Scripts/Chat/QuickResponse.prefab.meta
Labels: käyttöliittymä

#571 AvatarEditor moved to ProfiiliView + fixes
  Assets/MenuUi/Prefabs/Windows/Avatar/AvatarEditor.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/ProfiiliView.prefab
  Assets/MenuUi/Scripts/AvatarEditor/FeaturePicker.cs
  Assets/MenuUi/Scripts/PlayerProfile/ProfileMenuTabs.cs
Labels: käyttöliittymä

#573 UI/daily task/feature/connect daily task server calls
  Assets/Altzone/Scripts/Model/Poco/Game/PlayerTask.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Scripts/DailyQuest/DailyQuest.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskManager.cs
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskOwnTask.cs
  Assets/MenuUi/Scripts/DailyQuest/PopupData.cs
Labels: käyttöliittymä

#576 Battle/fix - BattleUiHotfix
  Assets/QuantumUser/Scripts/Game/GameViewController.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Qtn/GridSetEvent.qtn
  Assets/QuantumUser/Simulation/Qtn/ViewInitEvent.qtn
  Assets/QuantumUser/Simulation/Qtn/ViewInitEvent.qtn.meta
  Assets/QuantumUser/Simulation/Scripts/Game/GameControlSystem.cs
Labels: battle

#586 Update to the Shop layout
  Assets/Altzone/Resources/RarityColourReference.asset
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPage/AntiqueShopItem Variant.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPage/BronzeShopItem.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPage/GoldShopItem Variant.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPage/SilverShopItem Variant.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPanels.prefab
  Assets/MenuUi/Prefabs/UI Components/TabLineBase.prefab
  Assets/MenuUi/Prefabs/Windows/OstoehdotuksetView.prefab
  Assets/MenuUi/Prefabs/Windows/OstoehdotuksetView.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Prefabs/Windows/ÄänestysView.prefab
  Assets/MenuUi/Prefabs/Windows/ÄänestysView.prefab.meta
  Assets/MenuUi/Scripts/Kauppa/Addmoney.cs
  Assets/MenuUi/Scripts/Kauppa/Addmoney.cs.meta
  Assets/MenuUi/Scripts/Kauppa/InteractScript.cs
  Assets/MenuUi/Scripts/Kauppa/InteractScript.cs.meta
  Assets/MenuUi/Scripts/Kauppa/ItemCopyVote.cs
  Assets/MenuUi/Scripts/Kauppa/ItemCopyVote.cs.meta
  Assets/MenuUi/Scripts/Kauppa/ShopToVote.cs
  Assets/MenuUi/Scripts/Kauppa/ShopToVote.cs.meta
  Assets/MenuUi/Scripts/Kauppa/VotingSystem.cs
  Assets/MenuUi/Scripts/Kauppa/VotingSystem.cs.meta
  Assets/MenuUi/Scripts/PlayerProfile/ProfileMenuTabs.cs
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
Labels: käyttöliittymä

#574 Battle/feature - BattleUI
  Assets/Altzone/Resources/Prefabs/BattleUiShared.meta
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiDiamonds.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiDiamonds.prefab.meta
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiGiveUpButton.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiGiveUpButton.prefab.meta
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiPlayerInfo.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiPlayerInfo.prefab.meta
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiTimer.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiTimer.prefab.meta
  Assets/Altzone/Scripts/BattleUiShared.meta
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElement.cs
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElement.cs.meta
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElementData.cs
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElementData.cs.meta
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMultiOrientationElement.cs
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMultiOrientationElement.cs.meta
  Assets/QuantumUser/Resources/Prefabs/Ui/BattleUi.prefab
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/View/Battle/Scripts/Game/BattleGameViewController.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiAnnouncementHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiCharacterButtonComponent.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiCharacterButtonComponent.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiController.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiDebugStatsOverlayHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiDiamondsHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiDiamondsHandler.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiGameOverHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiGiveUpButtonHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiGiveUpButtonHandler.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiPlayerInfoComponent.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiPlayerInfoComponent.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiPlayerInfoHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiPlayerInfoHandler.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiTimerHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiTimerHandler.cs.meta
Labels: battle

#587 Battle/feature - PlayerHitboxCollisionTypes
  Assets/QuantumUser/Simulation/Battle/Scripts/Projectile/BattleProjectileQSystem.cs
Labels: Quantum, battle

#590 Updated the AdEditor and made it save the values within properly.
  Assets/Altzone/Resources/Data/AdDecorationReference.asset
  Assets/Altzone/Resources/Data/AdDecorationReference.asset.meta
  Assets/Altzone/Scripts/Model/Poco/Clan/AdData.cs
  Assets/Altzone/Scripts/Model/Poco/Clan/AdData.cs.meta
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanData.cs
  Assets/Altzone/Scripts/Reference Sheets/AdDecorationReference.cs
  Assets/Altzone/Scripts/Reference Sheets/AdDecorationReference.cs.meta
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempBackToTheFuture.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempDistrict9.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempDune.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempJaws.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempParasite.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempShining.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempSpaceOdessey.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempUp.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempWalle.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondHandBorderTempWorldwarZ.png.meta
  Assets/MenuUi/Graphics/ShopGraphics/Secondhand/SecondhandBorderGreed.png.meta
  Assets/MenuUi/Prefabs/ShopPrefabs/AdPoster.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/AdPoster.prefab.meta
  Assets/MenuUi/Prefabs/ShopPrefabs/ColourButton.prefab
  Assets/MenuUi/Prefabs/ShopPrefabs/ColourButton.prefab.meta
  Assets/MenuUi/Prefabs/ShopPrefabs/ShopPanels.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdEditor.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/BorderFrame.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/BorderFrame.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Scripts/ShopAd/AdEditor.cs
  Assets/MenuUi/Scripts/ShopAd/AdPosterHandler.cs
  Assets/MenuUi/Scripts/ShopAd/AdPosterHandler.cs.meta
Labels: käyttöliittymä

#596 Added online players to be visible in home screen.
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/MenuUi/Prefabs/UI Components/OnlinePlayerText.prefab
  Assets/MenuUi/Prefabs/UI Components/OnlinePlayerText.prefab.meta
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
  Assets/OnlinePlayerHandler.cs
  Assets/OnlinePlayerHandler.cs.meta
  Assets/OnlinePlayerTextHandler.cs
  Assets/OnlinePlayerTextHandler.cs.meta
  Assets/Prg/WebRequests.cs
Labels: käyttöliittymä

#592 Battle/fix - SmallBattleFixes
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundNoGrid.png
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundNoGrid.png.meta
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer.prefab
  Assets/QuantumUser/Resources/Prefabs/Projectile/BattleProjectile.prefab
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
Labels: Quantum, battle

#598 UI/varasto/feature/voting
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanFurniture.cs
  Assets/Altzone/Scripts/ServerManager.cs
  Assets/Altzone/Scripts/Voting/PollData.cs
  Assets/MenuUi/Prefabs/UI Components/InvSlotObject.prefab
  Assets/MenuUi/Prefabs/Voting/A_vote.prefab
  Assets/MenuUi/Prefabs/Voting/Votes_list.prefab
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Scripts/Varasto/FurnitureSellHandler.cs
  Assets/MenuUi/Scripts/Varasto/FurnitureSellHandler.cs.meta
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
  Assets/MenuUi/Scripts/Varasto/InvSlotInfoHandler.cs
  Assets/MenuUi/Scripts/Varasto/StorageFurniture.cs
  Assets/MenuUi/Scripts/Voting/AanestysValikko.cs
  Assets/MenuUi/Scripts/Voting/AanestysValikko.cs.meta
  Assets/MenuUi/Scripts/Voting/AddPlayerHeads.cs
  Assets/MenuUi/Scripts/Voting/CountdownTimer.cs
  Assets/MenuUi/Scripts/Voting/CountdownTimer.cs.meta
  Assets/MenuUi/Scripts/Voting/DisableVoting.cs
  Assets/MenuUi/Scripts/Voting/DisableVoting.cs.meta
  Assets/MenuUi/Scripts/Voting/KauppaValikko.cs
  Assets/MenuUi/Scripts/Voting/KauppaValikko.cs.meta
  Assets/MenuUi/Scripts/Voting/Kohde.cs
  Assets/MenuUi/Scripts/Voting/Kohde.cs.meta
  Assets/MenuUi/Scripts/Voting/No_button.cs
  Assets/MenuUi/Scripts/Voting/No_button.cs.meta
  Assets/MenuUi/Scripts/Voting/PollManager.cs
  Assets/MenuUi/Scripts/Voting/PollObject.cs
  Assets/MenuUi/Scripts/Voting/PollPopup.cs
  Assets/MenuUi/Scripts/Voting/ReceiveInteractedObjectScript.cs
  Assets/MenuUi/Scripts/Voting/ReceiveInteractedObjectScript.cs.meta
  Assets/MenuUi/Scripts/Voting/Reset_voting_stats.cs
  Assets/MenuUi/Scripts/Voting/Reset_voting_stats.cs.meta
  Assets/MenuUi/Scripts/Voting/ResultLimitCode.cs
  Assets/MenuUi/Scripts/Voting/SaveValuesScript.cs
  Assets/MenuUi/Scripts/Voting/SaveValuesScript.cs.meta
  Assets/MenuUi/Scripts/Voting/Set_vote_amount.cs
  Assets/MenuUi/Scripts/Voting/Set_vote_amount.cs.meta
  Assets/MenuUi/Scripts/Voting/Timer_Controller.cs
  Assets/MenuUi/Scripts/Voting/Timer_Controller.cs.meta
  Assets/MenuUi/Scripts/Voting/Vote_amount.cs
  Assets/MenuUi/Scripts/Voting/Vote_amount.cs.meta
  Assets/MenuUi/Scripts/Voting/Vote_bar.cs
  Assets/MenuUi/Scripts/Voting/Vote_bar.cs.meta
  Assets/MenuUi/Scripts/Voting/Winner_calculator.cs
  Assets/MenuUi/Scripts/Voting/Winner_calculator.cs.meta
  Assets/MenuUi/Scripts/Voting/Yes_button.cs
  Assets/MenuUi/Scripts/Voting/Yes_button.cs.meta
Labels: käyttöliittymä

#594 Battle UI editor created
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiDiamonds.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiGiveUpButton.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiPlayerInfo.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiTimer.prefab
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElement.cs
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMovableElementData.cs
  Assets/Altzone/Scripts/BattleUiShared/BattleUiMultiOrientationElement.cs
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorChangeOrientation.png
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorChangeOrientation.png.meta
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorFlip.png
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorFlip.png.meta
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorScaleHandle.png
  Assets/MenuUi/Graphics/SettingsGraphics/SettingsBattleUiEditorScaleHandle.png.meta
  Assets/MenuUi/Prefabs/Settings.meta
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor.meta
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditingComponent.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditingComponent.prefab.meta
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditor.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditor.prefab.meta
  Assets/MenuUi/Scripts/Settings/BattleUiEditor.meta
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditingComponent.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditingComponent.cs.meta
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditor.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditor.cs.meta
  Assets/MenuUi/Scripts/Settings/SettingsCarrier.cs
Labels: käyttöliittymä

#604 BattleUiEditor control button fixes
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditingComponent.cs
Labels: käyttöliittymä

#605 Streamlined creating custom room
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Resources/GameTypeReference.asset
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
Labels: käyttöliittymä

#607 Updated CharacterGallery and popups graphics
  Assets/MenuUi/Graphics/CommonGraphics/CommonBoxBase.png.meta
  Assets/MenuUi/Graphics/CommonGraphics/CommonBoxLowerHalf.png.meta
  Assets/MenuUi/Graphics/CommonGraphics/CommonBoxUpperHalf.png.meta
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/CharacterInventorySlot.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/InfoPanel.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/StatPanel.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/CharacterSlot.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/GalleryCharacter.cs
Labels: käyttöliittymä

#608 Updated InvSlotObject to use new UI assets
  Assets/MenuUi/Prefabs/UI Components/InvSlotObject.prefab
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
Labels: käyttöliittymä

#614 Fixed battle popup selected character class colors
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/BattlePopupSelectedCharacter.prefab
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
Labels: bug, käyttöliittymä

#624 Added more furniture.
  Assets/Altzone/Scripts/Model/Poco/Game/GameFurniture.cs
  Assets/Altzone/Scripts/Reference Sheets/StorageFurnitureReference.asset
  Assets/Altzone/Scripts/Reference Sheets/StorageFurnitureReference.cs
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/ElementKipuPlant.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuChair.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuCupboardOpen.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuCupboard_closed.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuCupboard_open.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuSofa.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Kipu/FurnitureKipuTable.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/KylmaTulevaisuus/FurnitureKylmaTHologram.PNG.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/KylmaTulevaisuus/FurnitureKylmaTSofa.PNG.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Uni/FurnitureUniBed.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Uni/FurnitureUniClosetClosed.png.meta
  Assets/MenuUi/Graphics/FurnitureGraphics/Uni/FurnitureUniClosetOpen.png.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Hologram_ColdFuture_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Hologram_ColdFuture_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Hologram_ColdFuture_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Hologram_ColdFuture_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Sofa_ColdFuture_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Sofa_ColdFuture_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Sofa_ColdFuture_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/ColdFuture/Sofa_ColdFuture_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/FurnitureBuilder.cs
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Chair_Kipu_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Chair_Kipu_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Chair_Kipu_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Chair_Kipu_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Closet_Kipu_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Closet_Kipu_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Closet_Kipu_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Closet_Kipu_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Plant_Kipu_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Plant_Kipu_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Plant_Kipu_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Plant_Kipu_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Sofa_Kipu_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Sofa_Kipu_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Sofa_Kipu_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Sofa_Kipu_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Table_Kipu_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Table_Kipu_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Table_Kipu_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Kipu/Table_Kipu_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Bed_Uni_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Bed_Uni_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Bed_Uni_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Bed_Uni_FurnitureImage.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Closet_Uni_Furniture.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Closet_Uni_Furniture.prefab.meta
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Closet_Uni_FurnitureImage.prefab
  Assets/MenuUi/Prefabs/Windows/SoulHome/Furniture Assets/Uni/Closet_Uni_FurnitureImage.prefab.meta
  Assets/MenuUi/Resources/SoulhomeFurnitureReference.asset
  Assets/MenuUi/Scripts/ReferenceSheets/SoulHomeFurnitureReference.cs
  Assets/MenuUi/Scripts/SoulHome/Furniture.cs
  Assets/MenuUi/Scripts/SoulHome/FurnitureHandling.cs
Labels: käyttöliittymä

#627 Refactored the AvatarVisualData and added the AvatarData fetching to and from server.
  Assets/Altzone/Scripts/AltMonoBehaviour.cs
  Assets/Altzone/Scripts/Model/Poco/Player/AvatarData.cs
  Assets/Altzone/Scripts/Model/Poco/Player/PlayerData.cs
  Assets/Altzone/Scripts/Model/Poco/Player/ServerPlayer.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarEditorController.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarFaceLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarVisualDataScriptableObject.cs
  Assets/MenuUi/Scripts/AvatarEditor/ColorPicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/FeaturePicker.cs
  Assets/MenuUi/Scripts/AvatarEditor/PlayerAvatar.cs
Labels: käyttöliittymä

#629 Added conversation lines to battlestory and updated the layout.
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayBackground.png.meta
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStart.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStartHandler.cs
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStartHandler.cs.meta
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStory.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStoryController.cs
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStoryLineHandler.cs
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStoryLineHandler.cs.meta
  Assets/MenuUi/Scripts/Chat/ChatMessageScript.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/Sedgwick Ave Display/SedgwickAveDisplay-Regular SDF.asset
Labels: käyttöliittymä
