Repository Alt-Org/Altzone, pull requests merged in 2025-05, with the labels that each got.

#631 Grid and arena options and fixes for BattleUiEditor
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditingComponent.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditor.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/GridLine.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/GridLine.prefab.meta
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditingComponent.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditor.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/GridController.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/GridController.cs.meta
  Assets/MenuUi/Scripts/Settings/SettingsCarrier.cs
Labels: käyttöliittymä

#632 Clan listing updates
  Assets/MenuUi/Prefabs/Clan/ClanSearch.prefab
  Assets/MenuUi/Prefabs/Clan/ClanSearchListItem.prefab
  Assets/MenuUi/Prefabs/Windows/Clan/ClanSearchView.prefab
  Assets/MenuUi/Scripts/Clan/ClanListing.cs
  Assets/MenuUi/Scripts/Clan/ClanSearchPopup.cs
  Assets/MenuUi/Scripts/Clan/ClanSearchPopup.cs.meta
  Assets/MenuUi/Scripts/Clan/ClanSearchView.cs
Labels: käyttöliittymä

#639 UI/settings/refactor/window update
  Assets/MenuUi/Prefabs/Windows/Settings/Settings.asset
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab.meta
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsViewModified.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsViewModified.prefab.meta
Labels: käyttöliittymä

#644 Updated character names
  Assets/Altzone/Resources/Characters/CharacterSpec_101.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_103.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_201.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_203.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_204.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_301.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_302.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_401.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_402.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_403.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_404.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_501.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_502.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_503.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_601.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_602.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_603.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_604.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_701.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_702.asset
  Assets/Altzone/Resources/Characters/CharacterSpec_703.asset
Labels: käyttöliittymä

#649 Fixed unable to remove character bug
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/GalleryCharacter.prefab
Labels: bug, käyttöliittymä

#653 Updated Storage and Voting graphics and updated poll handling.
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Voting/A_vote.prefab
  Assets/MenuUi/Prefabs/Voting/Votes_list.prefab
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Scripts/Varasto/InvFront.cs
  Assets/MenuUi/Scripts/Varasto/InvSlotInfoHandler.cs
  Assets/MenuUi/Scripts/Voting/PollManager.cs
  Assets/MenuUi/Scripts/Voting/PollPopup.cs
  Assets/MenuUi/Scripts/Voting/VoteManager.cs
  Assets/MenuUi/Scripts/Voting/VotingPopupHandler.cs
  Assets/MenuUi/Scripts/Voting/VotingPopupHandler.cs.meta
Labels: käyttöliittymä

#647 Battle popup bug fixes and streamlining entering a game.
  Assets/Altzone/Scripts/Photon/GameTypeEnum.cs
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/Photon/PhotonBattleRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonLobbyRoom.cs
  Assets/Altzone/Scripts/Photon/PhotonRealtimeClient.cs
  Assets/MenuUi/Prefabs/Navigation/BT_ALTZONE.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/GameTypeOption.prefab
  Assets/MenuUi/Resources/GameTypeReference.asset
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs
  Assets/MenuUi/Scripts/Lobby/BattlePopupPanelManager.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/InRoomController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/MatchmakingPanel.cs
  Assets/MenuUi/Scripts/Lobby/PhotonBattleLobbyRoom.cs
  Assets/MenuUi/Scripts/ReferenceSheets/GameTypeReference.cs
Labels: bug, käyttöliittymä

#654 Updated story panels for Intro Story
  Assets/MenuUi/Graphics/CommonGraphics/ArrowLeft.png
  Assets/MenuUi/Graphics/CommonGraphics/ArrowLeft.png.meta
  Assets/MenuUi/Graphics/CommonGraphics/ArrowRight.png
  Assets/MenuUi/Graphics/CommonGraphics/ArrowRight.png.meta
  Assets/MenuUi/Graphics/CommonGraphics/Esittely.jpg
  Assets/MenuUi/Graphics/CommonGraphics/Esittely.jpg.meta
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka (7).jpg
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka (7).jpg.meta
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka.jpg
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka.jpg.meta
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka2.jpg
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka2.jpg.meta
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka3.jpg
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka3.jpg.meta
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka4.png
  Assets/MenuUi/Graphics/CommonGraphics/Tapahtumapaikka4.png.meta
  Assets/MenuUi/Introduction/Graphics/Koulukiusaaja.jpg
  Assets/MenuUi/Introduction/Graphics/Property_1_100.png
  Assets/MenuUi/Introduction/Graphics/Property_1_100.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_200.png
  Assets/MenuUi/Introduction/Graphics/Property_1_200.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_300.png
  Assets/MenuUi/Introduction/Graphics/Property_1_300.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_400.png
  Assets/MenuUi/Introduction/Graphics/Property_1_400.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_500.png
  Assets/MenuUi/Introduction/Graphics/Property_1_500.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_600.png
  Assets/MenuUi/Introduction/Graphics/Property_1_600.png.meta
  Assets/MenuUi/Introduction/Graphics/Property_1_700.png
  Assets/MenuUi/Introduction/Graphics/Property_1_700.png.meta
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (1).jpg
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (1).jpg.meta
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (2).jpg
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (2).jpg.meta
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (3).jpg
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka (3).jpg.meta
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka.jpg
  Assets/MenuUi/Introduction/Graphics/Tapahtumapaikka.jpg.meta
  Assets/MenuUi/Introduction/Graphics/VALITSE komponentti'.jpg
  Assets/MenuUi/Introduction/Graphics/VALITSE komponentti'.jpg.meta
  Assets/MenuUi/Prefabs/Windows/IntroStory/CharacterIntroduction.prefab
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Scripts/SwipeNavigation/IntroSwipeUI.cs
  Assets/MenuUi/Scripts/SwipeNavigation/IntroSwipeUI.cs.meta
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeUI.cs
Labels: käyttöliittymä

#656 Origin/UI/varasto/add/stall
  Assets/MenuUi/Prefabs/Canvas/UICanvas.prefab
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterStatsWindow/CharacterInfoPanel.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdCard.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/Ad/AdCard.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/FurnitureSlotCard.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/FurnitureSlotCard.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/Koju.asset
  Assets/MenuUi/Prefabs/Windows/ClanStall/Koju.asset.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuContent.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuContent.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuSlotObject.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuSlotObject.prefab.meta
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuView.prefab
  Assets/MenuUi/Prefabs/Windows/ClanStall/KojuView.prefab.meta
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
Labels: käyttöliittymä

#666 Battle/refactor - PlayerManager
  Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs
Labels: Quantum, battle

#676 Battle/feature - Created 8 wide wall prefab, added into game scene
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType3.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType3.prefab.meta
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType3EntityPrototype.qprototype
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType3EntityPrototype.qprototype.meta
  Assets/QuantumUser/Resources/Specs/BattleArenaQSpec.asset
  Assets/QuantumUser/Resources/Specs/BattleSoulWallQSpec.asset
Labels: Quantum, battle

#678 Added CustomEditor to DailyTaskProgressListener
  Assets/MenuUi/Scripts/DailyQuest/DailyTaskProgressListener.cs
Labels: käyttöliittymä

#680 New start animation for Battle Start
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplay1.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplay2.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplay3.png.meta
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStart.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStartHandler.cs
Labels: käyttöliittymä

#681 Photon event message objects are now serialized to byte array
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/Altzone/Scripts/PhotonSerializer.cs
  Assets/Altzone/Scripts/PhotonSerializer.cs.meta
Labels: Photon Realtime

#667 Fixed bug that resetting default ui layout didn't trigger unsaved changes
  Assets/Altzone/Scripts/Settings/SettingsCarrier.cs
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditor.cs
Labels: bug, käyttöliittymä

#684 Battle/feature - Lightrays
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayBlueMedium.png.meta
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayBlueNarrow.png.meta
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayBlueWide.png.meta
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayRedMedium.png.meta
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayRedNarrow.png.meta
  Assets/QuantumUser/Resources/Graphics/Lightrays/BattleLightrayRedWide.png.meta
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleLightrayEffectViewController.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleLightrayEffectViewController.prefab.meta
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/Simulation/Battle/Qtn/Effects.meta
  Assets/QuantumUser/Simulation/Battle/Qtn/Effects/BattleLightrayEffect.qtn
  Assets/QuantumUser/Simulation/Battle/Qtn/Effects/BattleLightrayEffect.qtn.meta
  Assets/QuantumUser/Simulation/Battle/Qtn/Game/BattleEvents.qtn
  Assets/QuantumUser/Simulation/Battle/Qtn/SoulWall/BattleSoulWall.qtn
  Assets/QuantumUser/Simulation/Battle/Scripts/SoulWall/BattleSoulWallQSystem.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/View/Battle/Scripts/Effects/BattleLightrayEffectViewController.cs
  Assets/QuantumUser/View/Battle/Scripts/Effects/BattleLightrayEffectViewController.cs.meta
  Assets/QuantumUser/View/Battle/Scripts/Game/BattleGameViewController.cs
  Assets/QuantumUser/View/Generated/QPrototypeBattleSoulWallQComponent.cs
  Assets/QuantumUser/View/Generated/Quantum.CodeGen.UnityPrototypeAdapters.cs
Labels: Quantum, battle

#688 Battle/feature - Local player indicator
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer.prefab
  Assets/QuantumUser/View/Battle/Scripts/Player/BattlePlayerViewController.cs
  Assets/QuantumUser/View/Battle/Scripts/Player/BattlePlayerViewController.cs.meta
Labels: battle

#690 Added victory and defeat screens to battle story.
  Assets/MenuUi/Animations/BattleStory.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Anger.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Anger.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Joy.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Joy.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Love.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Love.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Playful.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Playful.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Reset.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Reset.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Sorrow.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character1_Sorrow.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Anger.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Anger.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Joy.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Joy.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Love.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Love.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Playful.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Playful.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Reset.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Reset.anim.meta
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Sorrow.anim
  Assets/MenuUi/Animations/BattleStory/BattleStory_Character2_Sorrow.anim.meta
  Assets/MenuUi/Animations/BattleStory/Character1.controller
  Assets/MenuUi/Animations/BattleStory/Character1.controller.meta
  Assets/MenuUi/Animations/BattleStory/Character2.controller
  Assets/MenuUi/Animations/BattleStory/Character2.controller.meta
  Assets/MenuUi/Animations/BattleStory/DefeatAnimation.anim
  Assets/MenuUi/Animations/BattleStory/DefeatAnimation.anim.meta
  Assets/MenuUi/Animations/BattleStory/Reset.anim
  Assets/MenuUi/Animations/BattleStory/Reset.anim.meta
  Assets/MenuUi/Animations/BattleStory/VictoryAnimation.anim
  Assets/MenuUi/Animations/BattleStory/VictoryAnimation.anim.meta
  Assets/MenuUi/Animations/BattleStory/VictoryDefeatAnimation.controller
  Assets/MenuUi/Animations/BattleStory/VictoryDefeatAnimation.controller.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayLoose.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayLoose2.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayLoose3.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayWin1.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayWin2.png.meta
  Assets/MenuUi/Graphics/BattleReplayGraphics/BattleReplayWin3.png.meta
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStory.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStoryController.cs
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
Labels: käyttöliittymä

#689 Fixed Popup bugs
  Assets/MenuUi/Prefabs/DefenceScreen/CharacterGallery/EditingPanel.prefab
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/EditingPopup.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterStatsWindow/StatsWindowController.cs
Labels: käyttöliittymä

#686 BattlePopup bug fixes in player positioning and passing player slot and UserId info to Battle
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/GameTypeOption.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleQConfig.cs
  Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs
  Assets/QuantumUser/Simulation/RuntimePlayer.User.cs
Labels: bug, käyttöliittymä

#692 Added null check in case a player who is missing a position leaves the game
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
Labels: bug, käyttöliittymä

#693 Added a way to show other player avatar data
  Assets/MenuUi/Prefabs/Panels/TopPanel.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/ProfiiliView.prefab
  Assets/MenuUi/Scripts/AvatarEditor/AvatarDesignLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarFaceLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarLoader.cs
  Assets/MenuUi/Scripts/AvatarEditor/AvatarVisualDataScriptableObject.cs
Labels: käyttöliittymä

#698 Battle/feature - Projectile acceleration
  Assets/QuantumUser/Simulation/Battle/Qtn/Game/BattleGameSession.qtn
  Assets/QuantumUser/Simulation/Battle/Qtn/Projectile/BattleProjectile.qtn
  Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleGameControlQSystem.cs
  Assets/QuantumUser/Simulation/Battle/Scripts/Projectile/BattleProjectileQSystem.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
Labels: Quantum, battle

#704 Battle/feature - Layers and Projectile Reference
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1Background.png
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1Background.png.meta
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundExtended.png
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundExtended.png.meta
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundNoGrid.png
  Assets/QuantumUser/Resources/Graphics/Background/BattleArena1BackgroundNoGrid.png.meta
  Assets/QuantumUser/Resources/Prefabs/Diamonds/BattleDiamond.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer.prefab
  Assets/QuantumUser/Resources/Prefabs/Projectile/BattleProjectile.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType1.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType2.prefab
  Assets/QuantumUser/Resources/Prefabs/SoulWall/BattleSoulWallSegmentType3.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleLightrayEffectViewController.prefab
  Assets/QuantumUser/Resources/Prefabs/ViewController/BattleStoneCharacterViewController.prefab
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/View/Battle/Scripts/Game/BattleGameViewController.cs
  Assets/QuantumUser/View/Battle/Scripts/Projectile/BattleProjectileViewController.cs
  ProjectSettings/TagManager.asset
Labels: grafiikka, battle

#707 Profile/Leaderboard bug fixes
  Assets/Altzone/Scripts/Reference Sheets/AvatarDefaultReference.cs
  Assets/MenuUi/Scripts/Leaderboard/LeaderboardPodium.cs
  Assets/MenuUi/Scripts/Leaderboard/LeaderboardView.cs
  Assets/MenuUi/Scripts/PlayerProfile/ProfileMenu.cs
Labels: käyttöliittymä

#708 Clan search filter updates and connection to clan create
  Assets/Altzone/Scripts/Model/Poco/Clan/ClanSearchFilters.cs
  Assets/MenuUi/Prefabs/Clan/ClanSearch.prefab
  Assets/MenuUi/Prefabs/Windows/Clan/ClanSearchView.prefab
  Assets/MenuUi/Scripts/Clan/ClanSearchFiltersPanel.cs
  Assets/MenuUi/Scripts/Clan/ClanSearchView.cs
Labels: käyttöliittymä

#696 Updated Battle Popup selected characters visuals and added it to home screen
  Assets/MenuUi/Prefabs/Navigation/BT_ALTZONE.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/BattlePopupSelectedCharacter.prefab
  Assets/MenuUi/Prefabs/UI Components/Battle Popup/SelectedCharacters.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/KotiView.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Resources/GameTypeReference.asset
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/EditingPopup.cs
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/PieChartPreview.cs
  Assets/MenuUi/Scripts/Lobby/BattleButton/BattleButton.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/CreateRoomCustom.cs
  Assets/MenuUi/Scripts/Lobby/CreateRoom/MapAndRoomNameSelector.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/InLobbyController.cs
  Assets/MenuUi/Scripts/Lobby/InLobby/LobbyRoomListingController.cs
  Assets/MenuUi/Scripts/Lobby/InRoom/RoomSetupManager.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupCharacterSlotController.cs
  Assets/MenuUi/Scripts/Lobby/SelectedCharacters/BattlePopupSelectedCharacter.cs
  Assets/MenuUi/Scripts/PlayerProfile/TabChangeHandler.cs
  Assets/MenuUi/Scripts/Settings/SettingEditor.cs
  Assets/MenuUi/Scripts/SwipeNavigation/SwipeUI.cs
  Assets/MenuUi/Scripts/Window/DataCarrier.cs
Labels: käyttöliittymä

#712 Update BattleUiEditor control button visuals and fix missing background
  Assets/MenuUi/Prefabs/Panels/UIOverlayPanel.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditingComponent.prefab
  Assets/MenuUi/Prefabs/Settings/BattleUiEditor/BattleUiEditor.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Scripts/Settings/BattleUiEditor/BattleUiEditingComponent.cs
Labels: käyttöliittymä

#716 Restructured the tab handling in tabline
  Assets/MenuUi/Prefabs/UI Components/TabLineBase.prefab
  Assets/MenuUi/Prefabs/UI Components/TabObject.prefab
  Assets/MenuUi/Prefabs/UI Components/TabObject.prefab.meta
  Assets/MenuUi/Prefabs/Voting/Votes_list.prefab
  Assets/MenuUi/Prefabs/Windows/Clan/ClanSearchView.prefab
  Assets/MenuUi/Prefabs/Windows/DailyTask/DailyTaskView.prefab
  Assets/MenuUi/Prefabs/Windows/DefenceScreen/DefenceView.prefab
  Assets/MenuUi/Prefabs/Windows/HomeScreen/ProfiiliView.prefab
  Assets/MenuUi/Prefabs/Windows/InventoryScreen/VarastoView.prefab
  Assets/MenuUi/Prefabs/Windows/PlayerStats/LeaderboardView.prefab
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Prefabs/Windows/ShopScreen/ShopView.prefab
  Assets/MenuUi/Scripts/TabLine/TabLine.cs
  Assets/MenuUi/Scripts/TabLine/TabObjectHandler.cs
  Assets/MenuUi/Scripts/TabLine/TabObjectHandler.cs.meta
Labels: käyttöliittymä
