Repository Alt-Org/Altzone, pull requests merged in 2025-09, with the labels that each got.

#799 FIX/UI replaced null check with ID match in DefenceForceView
  Assets/MenuUi/Scripts/DefenceScreen/CharacterGallery/DefenceForceView.cs
Labels: käyttöliittymä

#800 Partial update the the profile window.
  Assets/MenuUi/Prefabs/Windows/HomeScreen/ProfiiliView.prefab
  Assets/MenuUi/Scripts/PlayerProfile/ProfileMenu.cs
Labels: käyttöliittymä

#809 Add setting to skip intro video
  Assets/Altzone/Scripts/Settings/SettingsCarrier.cs
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
  Assets/MenuUi/Scripts/Loader/GameLoader.cs
  Assets/MenuUi/Scripts/Loader/IntroVideoHandler.cs
  Assets/MenuUi/Scripts/Settings/SettingEditor.cs
Labels: käyttöliittymä

#850 Battle/test - Speed Override
  Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs
Labels: Quantum, battle

#848 Update SkipIntroVideo setting name
  Assets/MenuUi/Prefabs/Windows/Settings/SettingsView.prefab
Labels: käyttöliittymä

#876 Added jukebox tracks
  Assets/Altzone/Resources/Audio/MusicDataReference.asset
  Assets/MenuUi/Audio/Sielunkoti/Jukebox/Drifting Souls.mp3
  Assets/MenuUi/Audio/Sielunkoti/Jukebox/Drifting Souls.mp3.meta
  Assets/MenuUi/Audio/Sielunkoti/Jukebox/JukeboxMusicUnverse.mp3
  Assets/MenuUi/Audio/Sielunkoti/Jukebox/JukeboxMusicUnverse.mp3.meta
  Assets/MenuUi/Graphics/SoulHomeGraphics/Jukebox/Drifting SoulsCD-2.png
  Assets/MenuUi/Graphics/SoulHomeGraphics/Jukebox/Drifting SoulsCD-2.png.meta
  Assets/MenuUi/Graphics/SoulHomeGraphics/Jukebox/UniverseCD-2.png
  Assets/MenuUi/Graphics/SoulHomeGraphics/Jukebox/UniverseCD-2.png.meta
Labels: äänet

#888 Reverted Intro Video & Lowered Intro Story Volume
  Assets/MenuUi/Prefabs/Introduction/IntroVideo.prefab
  Assets/MenuUi/Prefabs/Windows/IntroStory/CharacterIntroduction.prefab
Labels: käyttöliittymä, äänet

#796 Battle/feature - Loading Screen
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiPlayerInfoLoadingScreen.prefab
  Assets/Altzone/Resources/Prefabs/BattleUiShared/BattleUiPlayerInfoLoadingScreen.prefab.meta
  Assets/Altzone/Scripts/Photon/LobbyManager.cs
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStart.prefab
  Assets/MenuUi/Prefabs/Windows/BattleStory/BattleStartHandler.cs
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer101.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer104.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer203.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer204.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer301.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer302.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer402.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer403.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer501.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer601.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer602.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer701.png.meta
  Assets/QuantumUser/Resources/Graphics/Player/BattlePlayer703.png.meta
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer104Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer204Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer301Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer302Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer501Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer601Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer602Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer701Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Player/BattlePlayer703Character.prefab
  Assets/QuantumUser/Resources/Prefabs/Simulation/BattleSimulationData.prefab
  Assets/QuantumUser/Resources/Prefabs/Ui/BattleUi.prefab
  Assets/QuantumUser/Resources/QuantumMap.asset
  Assets/QuantumUser/Scenes/31-QuantumBattle.unity
  Assets/QuantumUser/Simulation/Battle/Qtn/Game/BattleEvents.qtn
  Assets/QuantumUser/Simulation/Battle/Qtn/Game/BattleGameSession.qtn
  Assets/QuantumUser/Simulation/Battle/Qtn/Game/BattleGameState.qtn
  Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleGameControlQSystem.cs
  Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleQConfig.cs
  Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Events.cs
  Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs
  Assets/QuantumUser/View/Battle/Scripts/Game/BattleGameViewController.cs
  Assets/QuantumUser/View/Battle/Scripts/Quantum.View.Battle.asmdef
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiAnnouncementHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiController.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiLoadScreenHandler.cs
  Assets/QuantumUser/View/Battle/Scripts/UI/BattleUiLoadScreenHandler.cs.meta
  Doc/Doxygen/Battle/additional-documentation/quantum-codegen/Game/qtn-BattleEvents.dox
  Doc/Doxygen/Battle/additional-documentation/quantum-codegen/Game/qtn-BattleGameSession.dox
  Doc/Doxygen/Battle/additional-documentation/quantum-codegen/Game/qtn-BattleGameState.dox
Labels: Quantum, battle

#893 Battle/refactor - Class Manager Error Messages
  Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerClassManager.cs
Labels: Quantum, battle
